name: Deployment pipeline
env:
  BACKEND_PORT: 5173 # Port number from playwright config
on:
  push:
    branches:
      - main
      - e2e

jobs:
  Backend_lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Write .env file
        uses: varunkumar/create-env-action@f3700ac2e8f204a34720c3f8229b29e456b6bcff

        with:
          path: ${{github.workspace}}
          env: |
            TEST_MONGODB_URI = ${{secrets.TEST_MONGODB_URI}}
            SECRET = ${{secrets.SECRET}}
            PORT = ${{env.BACKEND_PORT}}
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      
  Frontend_lint_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
  
  E2E_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps
      
      - name: Write .env file
        uses: varunkumar/create-env-action@f3700ac2e8f204a34720c3f8229b29e456b6bcff

        with:
          path: ${{github.workspace}}
          env: |
            TEST_MONGODB_URI = ${{secrets.TEST_MONGODB_URI}}
            SECRET = ${{secrets.SECRET}}
            PORT = ${{env.BACKEND_PORT}}
      - name: Build frontend
        run: |
          cd $GITHUB_WORKSPACE
          ./build_frontend.sh
      - name: Run backend
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm run start:test &
      - name: E2E tests
        run:
          cd e2e
          npm run test
